//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Treinamento.Presentation.WebMVC.PedidosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PedidosService.IPedidosService")]
    public interface IPedidosService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/RetornarItens", ReplyAction="http://tempuri.org/IPedidosService/RetornarItensResponse")]
        Treinamento.Entities.Pedido[] RetornarItens();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/RetornarItens", ReplyAction="http://tempuri.org/IPedidosService/RetornarItensResponse")]
        System.Threading.Tasks.Task<Treinamento.Entities.Pedido[]> RetornarItensAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/GravarPedido", ReplyAction="http://tempuri.org/IPedidosService/GravarPedidoResponse")]
        Treinamento.Entities.Pedido GravarPedido(Treinamento.Entities.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/GravarPedido", ReplyAction="http://tempuri.org/IPedidosService/GravarPedidoResponse")]
        System.Threading.Tasks.Task<Treinamento.Entities.Pedido> GravarPedidoAsync(Treinamento.Entities.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/AtualizarPedido", ReplyAction="http://tempuri.org/IPedidosService/AtualizarPedidoResponse")]
        void AtualizarPedido(Treinamento.Entities.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/AtualizarPedido", ReplyAction="http://tempuri.org/IPedidosService/AtualizarPedidoResponse")]
        System.Threading.Tasks.Task AtualizarPedidoAsync(Treinamento.Entities.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/ExcluirPedido", ReplyAction="http://tempuri.org/IPedidosService/ExcluirPedidoResponse")]
        void ExcluirPedido(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/ExcluirPedido", ReplyAction="http://tempuri.org/IPedidosService/ExcluirPedidoResponse")]
        System.Threading.Tasks.Task ExcluirPedidoAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/RetornarPedido", ReplyAction="http://tempuri.org/IPedidosService/RetornarPedidoResponse")]
        Treinamento.Entities.Pedido RetornarPedido(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidosService/RetornarPedido", ReplyAction="http://tempuri.org/IPedidosService/RetornarPedidoResponse")]
        System.Threading.Tasks.Task<Treinamento.Entities.Pedido> RetornarPedidoAsync(int codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidosServiceChannel : Treinamento.Presentation.WebMVC.PedidosService.IPedidosService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidosServiceClient : System.ServiceModel.ClientBase<Treinamento.Presentation.WebMVC.PedidosService.IPedidosService>, Treinamento.Presentation.WebMVC.PedidosService.IPedidosService {
        
        public PedidosServiceClient() {
        }
        
        public PedidosServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidosServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Treinamento.Entities.Pedido[] RetornarItens() {
            return base.Channel.RetornarItens();
        }
        
        public System.Threading.Tasks.Task<Treinamento.Entities.Pedido[]> RetornarItensAsync() {
            return base.Channel.RetornarItensAsync();
        }
        
        public Treinamento.Entities.Pedido GravarPedido(Treinamento.Entities.Pedido pedido) {
            return base.Channel.GravarPedido(pedido);
        }
        
        public System.Threading.Tasks.Task<Treinamento.Entities.Pedido> GravarPedidoAsync(Treinamento.Entities.Pedido pedido) {
            return base.Channel.GravarPedidoAsync(pedido);
        }
        
        public void AtualizarPedido(Treinamento.Entities.Pedido pedido) {
            base.Channel.AtualizarPedido(pedido);
        }
        
        public System.Threading.Tasks.Task AtualizarPedidoAsync(Treinamento.Entities.Pedido pedido) {
            return base.Channel.AtualizarPedidoAsync(pedido);
        }
        
        public void ExcluirPedido(int codigo) {
            base.Channel.ExcluirPedido(codigo);
        }
        
        public System.Threading.Tasks.Task ExcluirPedidoAsync(int codigo) {
            return base.Channel.ExcluirPedidoAsync(codigo);
        }
        
        public Treinamento.Entities.Pedido RetornarPedido(int codigo) {
            return base.Channel.RetornarPedido(codigo);
        }
        
        public System.Threading.Tasks.Task<Treinamento.Entities.Pedido> RetornarPedidoAsync(int codigo) {
            return base.Channel.RetornarPedidoAsync(codigo);
        }
    }
}
